import fs from "fs";
import path from "path";
import type { Product } from "@/types";

// ============================================================
// Snapshot reader — zero-DB-query rendering for home & category.
//
// Snapshots are generated by the backend (generate_snapshots.py)
// and committed / deployed as static JSON under public/data/snapshots/.
//
// If a snapshot is missing, these functions return null and the
// calling page falls back to its DB-backed path.
// ============================================================

const SNAPSHOT_DIR = path.join(process.cwd(), "public", "data", "snapshots");

// ── Home ──

export interface HomeCategoryEntry {
  key: string;
  count: number;
  atLowest: number;
}

export interface FeaturedProduct extends Product {
  dropPct: number;
  savings: number;
}

export interface HomeSnapshot {
  generated: string;
  categories: HomeCategoryEntry[];
  featured: FeaturedProduct[];
}

// ── Category ──

export interface RetailerCount {
  name: string;
  count: number;
}

export interface CategoryStats {
  totalProducts: number;
  avgPrice: number;
  medianPrice: number;
  atLowest: number;
  withHistory: number;
  retailers: RetailerCount[];
}

export interface BrandStat {
  name: string;
  count: number;
  avgPrice: number;
  minPrice: number;
  deals: number;
}

export interface CategorySnapshot {
  generated: string;
  products: Product[];
  catStats: CategoryStats;
  brandStats: BrandStat[];
}

// ── Readers ──

function readJson<T>(filePath: string): T | null {
  if (!fs.existsSync(filePath)) return null;
  try {
    return JSON.parse(fs.readFileSync(filePath, "utf-8")) as T;
  } catch {
    return null;
  }
}

export function getHomeSnapshot(): HomeSnapshot | null {
  return readJson<HomeSnapshot>(path.join(SNAPSHOT_DIR, "home.json"));
}

export function getCategorySnapshot(slug: string): CategorySnapshot | null {
  return readJson<CategorySnapshot>(
    path.join(SNAPSHOT_DIR, "category", `${slug}.json`)
  );
}

export function listSnapshotCategories(): string[] {
  const dir = path.join(SNAPSHOT_DIR, "category");
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".json"))
    .map((f) => f.replace(/\.json$/, ""));
}
