-- ─────────────────────────────────────────────────────────────────────────
-- TrackAura · Canonical Entity Schema (Phase 0, Week 1)
-- ─────────────────────────────────────────────────────────────────────────
-- Creates the seven new tables that will replace canonical_products over
-- the next 6-12 months. Per ARCHITECTURE.md §3:
--
--   "The current canonical_products table is the v0 electronics catalog.
--    It stays running. We build a new set of generic tables alongside it
--    and migrate category-by-category. Zero-downtime. Live site keeps
--    working on old tables. New tables come online as categories migrate."
--
-- What this file does:
--   - Creates the seven new tables with indexes and foreign keys
--   - Enables pg_trgm extension (required for §4 T2 fuzzy matching)
--   - Creates canonical_entities_view unioning old and new tables
--   - Grants SELECT/INSERT/UPDATE/DELETE to anon and authenticated roles
--
-- What this file does NOT do:
--   - Populate any new table (that is the GPU migration script, Week 1 B)
--   - Touch canonical_products, products, or price_points (old tables)
--   - Change any existing RPC (frontend keeps reading from old tables
--     until Week 4 adapter work)
--
-- Safety:
--   - All CREATE statements use IF NOT EXISTS or OR REPLACE — safe to re-run
--   - No DROP, no DELETE, no data mutation
--   - RLS left off on all new tables (no user data yet)
--
-- How to run:
--   Supabase dashboard → SQL Editor → paste this file → Run
--   Expected runtime: < 10 seconds
--   After running, scroll to "VERIFICATION QUERIES" at the bottom and
--   run those separately to confirm success.
--
-- Deviations from ARCHITECTURE.md §3 (intentional, documented):
--   - Added created_at to catalog_sources and entity_source_mappings
--     (not in spec, useful for debugging; zero downside)
--   - Chose ON DELETE CASCADE for attribute/relationship/listing/observation
--     FKs (spec silent on delete behavior; these are entity-owned data)
--   - Chose ON DELETE SET NULL for parent_entity_id (preserves children
--     when a parent is removed)
--   - Chose ON DELETE RESTRICT for entity_source_mappings.source_id
--     (prevents accidental catalog-source deletion)
--   - canonical_entities_view uses UNION ALL with source_table discriminator
--     rather than dedup at view level — migration script is responsible for
--     ensuring uniqueness. Simpler and cheaper than cross-table dedup.
-- ─────────────────────────────────────────────────────────────────────────


-- ── 0. Extensions ──
-- pg_trgm powers Tier 2 (fuzzy match) of the entity resolution engine per §4.
-- Ships with Supabase; this is a no-op if already enabled.

CREATE EXTENSION IF NOT EXISTS pg_trgm;


-- ── 1.1 canonical_entities ──
-- The core identity table. One row per distinct real-world item.
-- Self-referential parent_entity_id enables the tree hierarchy (§3):
--   MacBook → MacBook Pro → MacBook Pro 16" → MacBook Pro 16" M3 Max → leaf

CREATE TABLE IF NOT EXISTS canonical_entities (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug               text        NOT NULL UNIQUE,
    canonical_name     text        NOT NULL,
    display_name       text,
    vertical           text        NOT NULL,
    entity_type        text,
    parent_entity_id   bigint      REFERENCES canonical_entities(id) ON DELETE SET NULL,
    brand              text,
    release_date       date,
    msrp_cad           numeric,
    msrp_currency      text        DEFAULT 'CAD',
    image_primary_url  text,
    description_md     text,
    created_at         timestamptz NOT NULL DEFAULT NOW(),
    updated_at         timestamptz NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE canonical_entities IS
'Core identity table. One row = one distinct real-world item (phone, GPU, card, LEGO set, watch). Replaces canonical_products over 6-12mo migration. Bible §3.';

COMMENT ON COLUMN canonical_entities.vertical IS
'Top-level category: electronics, tcg, lego, comics, watches. See bible §2 for phased rollout.';

COMMENT ON COLUMN canonical_entities.parent_entity_id IS
'Tree hierarchy: NULL for roots, parent id for variants. Bible §3.';


-- ── 1.2 entity_attributes ──
-- Structured metadata for variants (storage_gb, color, chip, generation).
-- UNIQUE(entity_id, attribute_key) prevents duplicate attributes per entity.
-- is_price_defining flags attributes whose values distinguish leaf variants
-- (and thus separate price tracking).

CREATE TABLE IF NOT EXISTS entity_attributes (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id             bigint  NOT NULL REFERENCES canonical_entities(id) ON DELETE CASCADE,
    attribute_key         text    NOT NULL,
    attribute_value       text,
    attribute_value_num   numeric,
    is_price_defining     boolean NOT NULL DEFAULT false,
    CONSTRAINT entity_attributes_unique_key UNIQUE (entity_id, attribute_key)
);

COMMENT ON TABLE entity_attributes IS
'Key-value variants/specs for entities. Sortable numerics go in attribute_value_num; free-form in attribute_value.';


-- ── 1.3 entity_relationships ──
-- Typed directed links between entities: predecessor/successor/variant_of/alternative_to.
-- Powers lineage navigation and SEO internal linking.

CREATE TABLE IF NOT EXISTS entity_relationships (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_entity_id   bigint NOT NULL REFERENCES canonical_entities(id) ON DELETE CASCADE,
    to_entity_id     bigint NOT NULL REFERENCES canonical_entities(id) ON DELETE CASCADE,
    relationship     text   NOT NULL,
    CONSTRAINT entity_relationships_valid_type CHECK (
        relationship IN ('predecessor', 'successor', 'variant_of', 'alternative_to')
    ),
    CONSTRAINT entity_relationships_not_self CHECK (from_entity_id <> to_entity_id),
    CONSTRAINT entity_relationships_unique UNIQUE (from_entity_id, to_entity_id, relationship)
);

COMMENT ON TABLE entity_relationships IS
'Directed, typed links between canonical_entities. Used for lineage (predecessor/successor), variant trees, and SEO cross-linking.';


-- ── 1.4 catalog_sources ──
-- External sources that populate canonical_entities. Each vertical has one
-- authoritative source (bible §5): TechPowerUp for GPUs, Scryfall for MTG,
-- BrickLink for LEGO, GoCollect for graded comics, etc.

CREATE TABLE IF NOT EXISTS catalog_sources (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           text        NOT NULL UNIQUE,
    vertical       text,
    kind           text        NOT NULL DEFAULT 'scraped',
    last_imported  timestamptz,
    notes          text,
    created_at     timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT catalog_sources_valid_kind CHECK (
        kind IN ('scraped', 'manual', 'api')
    )
);

COMMENT ON TABLE catalog_sources IS
'Where canonical_entities come from. TechPowerUp, TCGplayer, BrickLink, manufacturer sites, etc. Per bible §5.';


-- ── 1.5 entity_source_mappings ──
-- Links canonical_entities to their external IDs in catalog_sources.
-- Enables "show me the TechPowerUp page for this GPU" and dedup during import.

CREATE TABLE IF NOT EXISTS entity_source_mappings (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id          bigint      NOT NULL REFERENCES canonical_entities(id) ON DELETE CASCADE,
    source_id          bigint      NOT NULL REFERENCES catalog_sources(id) ON DELETE RESTRICT,
    external_id        text        NOT NULL,
    source_url         text,
    confidence         numeric,
    verified_by_human  boolean     NOT NULL DEFAULT false,
    created_at         timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT entity_source_mappings_valid_confidence CHECK (
        confidence IS NULL OR (confidence >= 0 AND confidence <= 1)
    ),
    CONSTRAINT entity_source_mappings_unique_external UNIQUE (source_id, external_id),
    CONSTRAINT entity_source_mappings_unique_entity UNIQUE (entity_id, source_id)
);

COMMENT ON TABLE entity_source_mappings IS
'Maps entities to their external IDs in catalog_sources. Enables provenance, dedup during import, and lookup of source URLs.';


-- ── 1.6 listings ──
-- Retailer listings pointing at canonical_entities. One listing per (retailer, URL).
-- Records entity_resolution outcome in match_confidence + match_source (§4).
-- Inactive listings kept for historical price continuity.

CREATE TABLE IF NOT EXISTS listings (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id         bigint      NOT NULL REFERENCES canonical_entities(id) ON DELETE CASCADE,
    retailer          text        NOT NULL,
    retailer_sku      text,
    url               text        NOT NULL,
    first_seen        timestamptz NOT NULL DEFAULT NOW(),
    last_seen         timestamptz NOT NULL DEFAULT NOW(),
    is_active         boolean     NOT NULL DEFAULT true,
    match_confidence  numeric,
    match_source      text,
    country_code      text        NOT NULL DEFAULT 'CA',
    CONSTRAINT listings_valid_confidence CHECK (
        match_confidence IS NULL OR (match_confidence >= 0 AND match_confidence <= 1)
    ),
    CONSTRAINT listings_valid_match_source CHECK (
        match_source IS NULL OR match_source IN ('exact_sku', 'fuzzy', 'llm', 'human', 'scraper_seed')
    ),
    CONSTRAINT listings_unique_url UNIQUE (retailer, url)
);

COMMENT ON TABLE listings IS
'Retailer listings keyed to canonical_entities. One row per (retailer, URL). Inactive listings retained for price history continuity.';


-- ── 1.7 price_observations ──
-- Time-series of price snapshots. Replaces price_points.
-- entity_id is denormalized (also derivable from listing_id) to enable
-- fast entity-level aggregations without a join.

CREATE TABLE IF NOT EXISTS price_observations (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id      bigint      NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    entity_id       bigint      NOT NULL REFERENCES canonical_entities(id) ON DELETE CASCADE,
    price           numeric     NOT NULL,
    currency        text        NOT NULL DEFAULT 'CAD',
    is_in_stock     boolean,
    is_openbox      boolean     NOT NULL DEFAULT false,
    observed_at     timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT price_observations_nonnegative CHECK (price >= 0)
);

COMMENT ON TABLE price_observations IS
'Price time series. One row per price check. Replaces price_points. entity_id denormalized for fast entity-level aggregation.';


-- ── 2. updated_at trigger for canonical_entities ──

CREATE OR REPLACE FUNCTION touch_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS canonical_entities_updated_at ON canonical_entities;
CREATE TRIGGER canonical_entities_updated_at
    BEFORE UPDATE ON canonical_entities
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();


-- ── 3. Indexes ──
-- Designed for the query patterns called out in bible §3 and §4.

-- canonical_entities: vertical filter + entity type, tree nav, brand filter
CREATE INDEX IF NOT EXISTS canonical_entities_vertical_idx
    ON canonical_entities (vertical, entity_type);
CREATE INDEX IF NOT EXISTS canonical_entities_parent_idx
    ON canonical_entities (parent_entity_id)
    WHERE parent_entity_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS canonical_entities_brand_idx
    ON canonical_entities (brand)
    WHERE brand IS NOT NULL;

-- Trigram index on canonical_name — powers T2 fuzzy matching (§4).
-- Query: WHERE brand = ? AND similarity(canonical_name, ?) > 0.85
-- Postgres combines this GIN scan with the brand btree above.
CREATE INDEX IF NOT EXISTS canonical_entities_name_trgm_idx
    ON canonical_entities USING GIN (canonical_name gin_trgm_ops);

-- entity_attributes: find all entities with a given attribute value, and
-- fast lookup of price-defining attributes for leaf detection.
CREATE INDEX IF NOT EXISTS entity_attributes_key_value_idx
    ON entity_attributes (attribute_key, attribute_value)
    WHERE attribute_value IS NOT NULL;
CREATE INDEX IF NOT EXISTS entity_attributes_price_defining_idx
    ON entity_attributes (entity_id)
    WHERE is_price_defining = true;

-- entity_relationships: reverse lookup (forward covered by UNIQUE constraint)
CREATE INDEX IF NOT EXISTS entity_relationships_reverse_idx
    ON entity_relationships (to_entity_id, relationship);

-- listings: entity lookup, active-only filter, SKU lookup
CREATE INDEX IF NOT EXISTS listings_entity_idx
    ON listings (entity_id);
CREATE INDEX IF NOT EXISTS listings_active_idx
    ON listings (entity_id, retailer)
    WHERE is_active = true;
CREATE INDEX IF NOT EXISTS listings_sku_idx
    ON listings (retailer, retailer_sku)
    WHERE retailer_sku IS NOT NULL;

-- price_observations: most-recent-price-per-listing and per-entity
CREATE INDEX IF NOT EXISTS price_observations_listing_idx
    ON price_observations (listing_id, observed_at DESC);
CREATE INDEX IF NOT EXISTS price_observations_entity_idx
    ON price_observations (entity_id, observed_at DESC);


-- ── 4. Transition view ──
-- Unions legacy canonical_products rows with new canonical_entities rows.
-- Provides a stable read surface while categories migrate one at a time.
-- Frontend will start reading from this view in Week 4.
--
-- Deliberately does NOT dedup: the migration script is the only process
-- that inserts into canonical_entities, and it must ensure no duplicates.
-- source_table discriminator lets queries filter or identify origin.

CREATE OR REPLACE VIEW canonical_entities_view AS
SELECT
    cp.id,
    cp.slug,
    cp.name                AS canonical_name,
    cp.name                AS display_name,
    'electronics'::text    AS vertical,
    COALESCE(cp.category, 'other') AS entity_type,
    NULL::bigint           AS parent_entity_id,
    cp.brand,
    NULL::date             AS release_date,
    NULL::numeric          AS msrp_cad,
    NULL::text             AS msrp_currency,
    cp.image_url           AS image_primary_url,
    NULL::text             AS description_md,
    cp.created_at,
    cp.updated_at,
    'canonical_products'::text AS source_table
FROM canonical_products cp

UNION ALL

SELECT
    ce.id,
    ce.slug,
    ce.canonical_name,
    ce.display_name,
    ce.vertical,
    ce.entity_type,
    ce.parent_entity_id,
    ce.brand,
    ce.release_date,
    ce.msrp_cad,
    ce.msrp_currency,
    ce.image_primary_url,
    ce.description_md,
    ce.created_at,
    ce.updated_at,
    'canonical_entities'::text AS source_table
FROM canonical_entities ce;

COMMENT ON VIEW canonical_entities_view IS
'Union of legacy canonical_products and new canonical_entities during migration. No view-level dedup — migration script guarantees uniqueness. source_table discriminator available for filtering. Frontend reads from this view starting Week 4.';


-- ── 5. Grants ──
-- Match the pattern established in supabase_migrations.sql.
-- RLS stays off; no user data in these tables.

GRANT SELECT, INSERT, UPDATE, DELETE ON canonical_entities       TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON entity_attributes        TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON entity_relationships     TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON catalog_sources          TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON entity_source_mappings   TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON listings                 TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON price_observations       TO authenticated;

GRANT SELECT ON canonical_entities      TO anon;
GRANT SELECT ON entity_attributes       TO anon;
GRANT SELECT ON entity_relationships    TO anon;
GRANT SELECT ON catalog_sources         TO anon;
GRANT SELECT ON entity_source_mappings  TO anon;
GRANT SELECT ON listings                TO anon;
GRANT SELECT ON price_observations      TO anon;

GRANT SELECT ON canonical_entities_view TO anon, authenticated;

-- Sequence USAGE so INSERT with default id value works.
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;


-- ─────────────────────────────────────────────────────────────────────────
-- VERIFICATION QUERIES
-- ─────────────────────────────────────────────────────────────────────────
-- Run these AFTER the above completes successfully to confirm everything
-- landed. Each comment block lists expected result.
-- ─────────────────────────────────────────────────────────────────────────

-- 1. All seven tables exist.  Expected: 7 rows.
-- SELECT table_name FROM information_schema.tables
-- WHERE table_schema = 'public' AND table_name IN (
--     'canonical_entities', 'entity_attributes', 'entity_relationships',
--     'listings', 'price_observations', 'catalog_sources', 'entity_source_mappings'
-- ) ORDER BY table_name;

-- 2. pg_trgm extension enabled.  Expected: 1 row (version e.g. 1.6).
-- SELECT extname, extversion FROM pg_extension WHERE extname = 'pg_trgm';

-- 3. Trigram GIN index exists (critical for §4 T2).  Expected: 1 row.
-- SELECT indexname FROM pg_indexes
-- WHERE tablename = 'canonical_entities' AND indexname LIKE '%trgm%';

-- 4. View returns the full canonical_products row count plus 0 new entities.
-- Expected: source_table='canonical_products', count = existing product count.
-- SELECT source_table, count(*) FROM canonical_entities_view GROUP BY source_table;

-- 5. All new tables empty (only the view shows legacy data).  Expected: 0 each.
-- SELECT 'canonical_entities'       AS t, count(*) FROM canonical_entities UNION ALL
-- SELECT 'entity_attributes',             count(*) FROM entity_attributes UNION ALL
-- SELECT 'entity_relationships',          count(*) FROM entity_relationships UNION ALL
-- SELECT 'listings',                      count(*) FROM listings UNION ALL
-- SELECT 'price_observations',            count(*) FROM price_observations UNION ALL
-- SELECT 'catalog_sources',               count(*) FROM catalog_sources UNION ALL
-- SELECT 'entity_source_mappings',        count(*) FROM entity_source_mappings;

-- 6. Legacy site queries still work.  Pick any RPC; should run unchanged.
-- SELECT * FROM home_top_categories(5);
-- SELECT * FROM home_featured_deals(5);

-- ─────────────────────────────────────────────────────────────────────────
-- End of Week 1 schema. Next: GPU migration script (Week 1 B).
-- ─────────────────────────────────────────────────────────────────────────
